name: DevOps CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
    steps:
      - uses: actions/checkout@v3
        with:
          path: .  # Ensures repo is cloned in the correct location
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - run: npm install && npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Deploying..."
